/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

import Component.BuyProductable;
import Model.Product;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import Component.ProductDetailObs;
import Service.ProductService;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author toey
 */
public class ToppingDialog extends javax.swing.JDialog implements ProductDetailObs {

    private Product product;
    private ArrayList<ProductDetailObs> productDetails;
    private ProductService productService;
    private ArrayList<BuyProductable> subs;

    /**
     * Creates new form ToppingDialog1
     */
    public ToppingDialog(java.awt.Frame parent, Product product) {
        super(parent, true);
        initComponents();
        this.productDetails = new ArrayList<ProductDetailObs>();
        this.productService = new ProductService();
        this.product = product;
        ImageIcon icon = new ImageIcon("./" + product.getName() + ".jpg");
        Image image = icon.getImage();
        int width = image.getWidth(null);
        int height = image.getHeight(null);
        Image newImage = image.getScaledInstance((int) ((90.0 * width) / height), 90, Image.SCALE_SMOOTH);
        icon.setImage(newImage);
        lblImg.setIcon(icon);
        lblProductName.setText(product.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgType = new javax.swing.ButtonGroup();
        btgSize = new javax.swing.ButtonGroup();
        btgTopping = new javax.swing.ButtonGroup();
        btgSweet = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtTopping2 = new javax.swing.JLabel();
        rbtBubble3 = new javax.swing.JRadioButton();
        rbtTopping5 = new javax.swing.JRadioButton();
        rbtWhipcream2 = new javax.swing.JRadioButton();
        rbtWhipcream3 = new javax.swing.JRadioButton();
        rbtWhipcream4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        txtTopping1 = new javax.swing.JLabel();
        rbtBubble1 = new javax.swing.JRadioButton();
        rbtTopping3 = new javax.swing.JRadioButton();
        rbtWhipcream1 = new javax.swing.JRadioButton();
        rbtBubble2 = new javax.swing.JRadioButton();
        rbtTopping4 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        rbtHot = new javax.swing.JRadioButton();
        rbtCold = new javax.swing.JRadioButton();
        rbtFrappe = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtTopping = new javax.swing.JLabel();
        rbtBubble = new javax.swing.JRadioButton();
        rbtTopping2 = new javax.swing.JRadioButton();
        rbtWhipcream = new javax.swing.JRadioButton();
        btnConfirm = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblImg.setBackground(new java.awt.Color(224, 205, 174));
        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setOpaque(true);

        lblProductName.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        lblProductName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductName.setText("Product Name");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txtTopping2.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        txtTopping2.setText("Sweet Level:");

        btgSweet.add(rbtBubble3);
        rbtBubble3.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtBubble3.setText("0%");
        rbtBubble3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtBubble3ActionPerformed(evt);
            }
        });

        btgSweet.add(rbtTopping5);
        rbtTopping5.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtTopping5.setText("25%");

        btgSweet.add(rbtWhipcream2);
        rbtWhipcream2.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtWhipcream2.setText("50%");

        btgSweet.add(rbtWhipcream3);
        rbtWhipcream3.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtWhipcream3.setText("100%");

        btgSweet.add(rbtWhipcream4);
        rbtWhipcream4.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtWhipcream4.setText("125%");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTopping2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(rbtBubble3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtTopping5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtWhipcream2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtWhipcream3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtWhipcream4)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTopping2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtBubble3)
                    .addComponent(rbtTopping5)
                    .addComponent(rbtWhipcream2)
                    .addComponent(rbtWhipcream3)
                    .addComponent(rbtWhipcream4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtTopping1.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        txtTopping1.setText("Topping:");

        btgTopping.add(rbtBubble1);
        rbtBubble1.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtBubble1.setText("Cheese  +10");

        btgTopping.add(rbtTopping3);
        rbtTopping3.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtTopping3.setText("Pearl  +10");

        btgTopping.add(rbtWhipcream1);
        rbtWhipcream1.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtWhipcream1.setText("HoneyPearl  +10");

        btgTopping.add(rbtBubble2);
        rbtBubble2.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtBubble2.setText("KonjacJelly  +10");

        btgTopping.add(rbtTopping4);
        rbtTopping4.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtTopping4.setText("FruitSalad  +10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTopping1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtBubble1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtTopping3)
                                .addGap(18, 18, 18)
                                .addComponent(rbtWhipcream1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtBubble2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtTopping4)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTopping1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtBubble1)
                    .addComponent(rbtTopping3)
                    .addComponent(rbtWhipcream1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtBubble2)
                    .addComponent(rbtTopping4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btgType.add(rbtHot);
        rbtHot.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtHot.setText("Hot  +0");

        btgType.add(rbtCold);
        rbtCold.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtCold.setText("Cold +10");
        rbtCold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtColdActionPerformed(evt);
            }
        });

        btgType.add(rbtFrappe);
        rbtFrappe.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtFrappe.setText("Frappe  +10");

        jLabel1.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        jLabel1.setText("Type:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(rbtHot)
                        .addGap(18, 18, 18)
                        .addComponent(rbtCold)
                        .addGap(18, 18, 18)
                        .addComponent(rbtFrappe)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtHot)
                    .addComponent(rbtCold)
                    .addComponent(rbtFrappe))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtTopping.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        txtTopping.setText("Size:");

        btgSize.add(rbtBubble);
        rbtBubble.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtBubble.setText("S +0");
        rbtBubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtBubbleActionPerformed(evt);
            }
        });

        btgSize.add(rbtTopping2);
        rbtTopping2.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtTopping2.setText("M +10");

        btgSize.add(rbtWhipcream);
        rbtWhipcream.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        rbtWhipcream.setText("L +15");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTopping))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(rbtBubble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtTopping2)
                        .addGap(18, 18, 18)
                        .addComponent(rbtWhipcream)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTopping)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtBubble)
                    .addComponent(rbtTopping2)
                    .addComponent(rbtWhipcream))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfirm.setBackground(new java.awt.Color(93, 156, 89));
        btnConfirm.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(231, 70, 70));
        jButton1.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirm)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(224, 205, 174));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblName.setFont(new java.awt.Font("Kanit", 1, 30)); // NOI18N
        lblName.setText("Topping");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblName)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearButtonRadioGroup();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearButtonRadioGroup() {
        // TODO add your handling code here:
        btgSize.clearSelection();
        btgSweet.clearSelection();
        btgType.clearSelection();
        btgTopping.clearSelection();
    }

    private void rbtColdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbtColdActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rbtColdActionPerformed

    private void rbtBubbleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbtBubbleActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rbtBubbleActionPerformed

    private void rbtBubble3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbtBubble3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rbtBubble3ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        // String sizeName =
        // productService.getSizes().get(btgSize.getButtonCount()).getName();
        // System.out.println(getSelectedIndex(btgSize));
        // System.out.println(btgSize.getElements().);
        int sizeId = getSelectedIndex(btgSize);
        int toppingId = getSelectedIndex(btgTopping);
        int sweetId = getSelectedIndex(btgSweet);
        int typeId = getSelectedIndex(btgType);
        System.out.println(sizeId);
        System.out.println(toppingId);
        System.out.println(sweetId);
        System.out.println(typeId);
        if (sizeId < 0 || sweetId < 0 || typeId < 0) {
            JOptionPane.showMessageDialog(this, "Form not cpmplele .");
            return;
        }
        String sizeName = productService.getSizes().get(sizeId).getName();
        float sizePrice = productService.getSizes().get(sizeId).getPrice();
        String sweetName = productService.getSweets().get(sweetId).getName();
        float sweetPrice = productService.getSweets().get(sweetId).getPrice();
        String typeName = productService.getTypes().get(typeId).getName();
        float typePrice = productService.getTypes().get(typeId).getPrice();
        String toppingName = "-";
        float toppingPrice = 0;
        if (toppingId >= 0) {
            toppingName = productService.getToppings().get(toppingId).getName();
            toppingPrice = productService.getToppings().get(toppingId).getPrice();
        }
        setDetailProduct(sizePrice, sizeName, toppingPrice, toppingName, sweetPrice, sweetName, typePrice, typeName);
        clearButtonRadioGroup();
        dispose();
    }// GEN-LAST:event_btnConfirmActionPerformed

    private int getSelectedIndex(ButtonGroup buttonGroup) {
        Enumeration<AbstractButton> buttons = buttonGroup.getElements();
        int index = 0;
        while (buttons.hasMoreElements()) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return index;
            }
            index++;
        }
        return -1; // No selection
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSize;
    private javax.swing.ButtonGroup btgSweet;
    private javax.swing.ButtonGroup btgTopping;
    private javax.swing.ButtonGroup btgType;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JRadioButton rbtBubble;
    private javax.swing.JRadioButton rbtBubble1;
    private javax.swing.JRadioButton rbtBubble2;
    private javax.swing.JRadioButton rbtBubble3;
    private javax.swing.JRadioButton rbtCold;
    private javax.swing.JRadioButton rbtFrappe;
    private javax.swing.JRadioButton rbtHot;
    private javax.swing.JRadioButton rbtTopping2;
    private javax.swing.JRadioButton rbtTopping3;
    private javax.swing.JRadioButton rbtTopping4;
    private javax.swing.JRadioButton rbtTopping5;
    private javax.swing.JRadioButton rbtWhipcream;
    private javax.swing.JRadioButton rbtWhipcream1;
    private javax.swing.JRadioButton rbtWhipcream2;
    private javax.swing.JRadioButton rbtWhipcream3;
    private javax.swing.JRadioButton rbtWhipcream4;
    private javax.swing.JLabel txtTopping;
    private javax.swing.JLabel txtTopping1;
    private javax.swing.JLabel txtTopping2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setDetailProduct(double sizePrice, String sizeName, double toppingPrice, String toppingName,
            double sweetPrice, String sweetName, double typePrice, String typeName) {
        System.out.println("Dialog.ToppingDialog.setDetailProduct()");
        for (ProductDetailObs productDetail : productDetails) {
            productDetail.setDetailProduct(sizePrice, sizeName, toppingPrice, toppingName, sweetPrice, sweetName,
                    typePrice, typeName);

        }
    }

    public void addSubscipber(ProductDetailObs productDetailObs) {
        productDetails.add(productDetailObs);
    }

}
