/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Component;

/**
 *
 * @author Chaiwat
 */
public class btnAddBuyStock extends javax.swing.JPanel {

    /**
     * Creates new form btnAddBuyStock
     */
    public btnAddBuyStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdAddBuyStock = new javax.swing.JLabel();

        cmdAddBuyStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageButton/cmdAdd.png"))); // NOI18N
        cmdAddBuyStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdAddBuyStockMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdAddBuyStock)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdAddBuyStock)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAddBuyStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAddBuyStockMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdAddBuyStockMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cmdAddBuyStock;
    // End of variables declaration//GEN-END:variables
}
