/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Component;

import Model.User;
import Page.CheckinCheckoutPanel;
import Service.UserService;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author toey
 */
public class NavigationBar extends javax.swing.JPanel implements ChagePage, LoginObs {

    private ArrayList<ChagePage> subscobers;
    private UserService userService;
    private List<User> list;
    private User editedUser;
    private ArrayList<LoginObs> loginObses;
    private CheckinCheckoutPanel checkinCheckoutPanel = new CheckinCheckoutPanel();

    /**
     * Creates new form Navigation
     */
    public NavigationBar() {
        initComponents();
        editedUser = new User();
        initComponents();
        loginObses = new ArrayList<>();
        subscobers = new ArrayList<ChagePage>();
        userService = new UserService();
        ImageIcon icon = new ImageIcon("./image.png");
        Image image = icon.getImage();
        int width = image.getWidth(null);
        int height = image.getHeight(null);
        Image newImage = image.getScaledInstance((int) (150.0 * ((float) width / height)), 150, Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newImage);
        lblLogo.setIcon(newIcon);

    }

    class JPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(138, 108, 81);
            Color color2 = new Color(245, 237, 231);
            GradientPaint gp = new GradientPaint(0, 0, color1, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new JPanelGradient();
        lblLogo = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();
        btnPos = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnEmp = new javax.swing.JButton();
        btnMat = new javax.swing.JButton();
        btnCico = new javax.swing.JButton();
        btnRentStore = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnCheckStock = new javax.swing.JButton();
        btnBuyStock = new javax.swing.JButton();
        btnHisMat = new javax.swing.JButton();
        btnSumSalary = new javax.swing.JButton();

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon("D:\\Soft dev\\Group Project\\Dcoffee\\DecoffeeAllForOneMark2\\image.png")); // NOI18N

        btnReport.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnReport.setText("Dashboard");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnPos.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnPos.setText("Point of Sell");
        btnPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosActionPerformed(evt);
            }
        });

        btnProduct.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnProduct.setText("Product");
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });

        btnUser.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnUser.setText("User");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        btnEmp.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnEmp.setText("Employee");
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });

        btnMat.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnMat.setText("Material");
        btnMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatActionPerformed(evt);
            }
        });

        btnCico.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnCico.setText("Check In/Out");
        btnCico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCicoActionPerformed(evt);
            }
        });

        btnRentStore.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnRentStore.setText("Rent Store");
        btnRentStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentStoreActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnCheckStock.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnCheckStock.setText("Check Stock");
        btnCheckStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckStockActionPerformed(evt);
            }
        });

        btnBuyStock.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnBuyStock.setText("Buy Stock");
        btnBuyStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyStockActionPerformed(evt);
            }
        });

        btnHisMat.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnHisMat.setText("History Material");
        btnHisMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHisMatActionPerformed(evt);
            }
        });

        btnSumSalary.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnSumSalary.setText("Summary Salary");
        btnSumSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumSalaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRentStore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPos, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnMat, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnCico, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnCheckStock, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnBuyStock, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnHisMat, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnSumSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHisMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuyStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSumSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRentStore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        chagePage("Main menu");
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosActionPerformed
        chagePage("POS");
    }//GEN-LAST:event_btnPosActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        chagePage("Product");
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        chagePage("User");
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
        chagePage("Employee");
    }//GEN-LAST:event_btnEmpActionPerformed

    private void btnMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatActionPerformed
        chagePage("Material");
    }//GEN-LAST:event_btnMatActionPerformed

    private void btnCicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCicoActionPerformed
        chagePage("Check In-Out");
    }//GEN-LAST:event_btnCicoActionPerformed

    private void btnRentStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentStoreActionPerformed
        chagePage("Rent Store");
    }//GEN-LAST:event_btnRentStoreActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            // User confirmed logout, so exit the application
            System.exit(0);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCheckStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckStockActionPerformed
        chagePage("Check Stock");
    }//GEN-LAST:event_btnCheckStockActionPerformed

    private void btnBuyStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyStockActionPerformed
        chagePage("BuyStock");
    }//GEN-LAST:event_btnBuyStockActionPerformed

    private void btnHisMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHisMatActionPerformed
        chagePage("HistoryMaterial");
    }//GEN-LAST:event_btnHisMatActionPerformed

    private void btnSumSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumSalaryActionPerformed
        chagePage("SS Main");
    }//GEN-LAST:event_btnSumSalaryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBuyStock;
    private javax.swing.JButton btnCheckStock;
    private javax.swing.JButton btnCico;
    private javax.swing.JButton btnEmp;
    private javax.swing.JButton btnHisMat;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMat;
    private javax.swing.JButton btnPos;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnRentStore;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSumSalary;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
@Override
    public void chagePage(String pageName) {
        for (ChagePage subscober : subscobers) {
            subscober.chagePage(pageName);

        }
    }

    public void addInSubs(ChagePage chagePage) {
        subscobers.add(chagePage);
    }

    public void addInSubsLogin(LoginObs loginOb) {
        loginObses.add(loginOb);
    }

    @Override
    public void loginData(User user) {
        for (LoginObs subscober : loginObses) {
            subscober.loginData(user);

        }
        editedUser = user;
        System.out.println("Component.NavigationBar.loginData() ::: " + editedUser);
        if (editedUser.getRole().equals("user")) {
            btnUser.setVisible(false);
            btnEmp.setVisible(false);
            btnSumSalary.setVisible(false);
            btnBuyStock.setVisible(false);
            btnRentStore.setVisible(false);

        } else {
            btnUser.setVisible(true);
            btnEmp.setVisible(true);
            btnSumSalary.setVisible(true);
            btnBuyStock.setVisible(true);
            btnRentStore.setVisible(true);
        }
    }
}
